spring:
  application:
    name: CulinariO

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 30000

  # Bloco SQL (Alinhado à esquerda)
  sql:
    init:
      mode: never

  # Bloco JPA (Agora alinhado corretamente com o sql e datasource!)
  jpa:
    open-in-view: true # Mantém a conexão aberta pro HTML funcionar
    hibernate:
      ddl-auto: create # ATENÇÃO: Vai apagar tudo na próxima reinicialização
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect